### ISSUE TITLE
copy type report error: Use of moved value 

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10427]
## Environment

* **IntelliJ Rust plugin version:** 0.4.195.5369-231-nightly
* **Rust toolchain version:** rustc 1.71.0-nightly (a368898de 2023-05-02)
* **IDE name and version:** Clion 2023.1.2
* **Operating system:** Archlinux

## Problem description
![image](https://user-images.githubusercontent.com/10096425/236003647-db31a17e-4d8b-407e-9d67-5fa05798b688.png)

the `fwmark` is u32, so it won't have a **Use of moved value** problem

I already run `cargo clean` and clean the ide cache but it doesn't work

**Comment by ThanePatrol** [comment]
Can confirm the same behavior on:

    IntelliJ Rust plugin version: 0.4.195.5369-231-nightly
    Rust toolchain version: rustc 1.71.0-nightly (a368898de 2023-05-02)
    IDE name and version: Intellij Ultimate 2023.1.1
    Operating system: PopOS

**Comment by vlad20012** [comment]
Hi! Thank you for the report!
The issue is 100% reproducible on the latest Rust nightly, but not on the stable.
I investigated that the Rust plugin can't expand an stdlib macro that implements `Copy` for primitive types (because of the latest changes in the stdlib) and hence the plugin doesn't know that primitive types implement `Copy`.
I'll investigate it further and try to fix it. As a workaround, you can try to use less recent Rust nightly version

**Comment by OptimisticPeach** [comment]
A good workaround is to (erroneously) manually implement `Copy` for the types you want:
```rs
impl Copy for usize {}
impl Copy for f32 {}
```
And then disabling this when you're actually compiling. I tend to write large chunks of code and don't compile very often, so this works for me, but if you find it cumbersome to do so, then write a feature that you never actually use and tell ij-rs to enable that feature when doing code analysis (by ticking the box in the `Cargo.toml`), but then don't compile your code with the feature. Place the `impl`s in a module only enabled by said feature.

**Comment by AlexTMjugador** [comment]
For reference, the latest nightly that doesn't exhibit this false positive is the one released on `2023-05-01`, which can be installed with `rustup toolchain install nightly-2023-05-01`.

**Comment by vlad20012** [comment]
The issue has been fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by tazz4843** [comment]
Can still reproduce this on 0.4.196.5400-231-nightly. I've followed all "Repair IDE" steps up to "Restart and Invalidate Caches", after which it breaks, so I can't follow any more.

rustc 1.72.0-nightly (e6d4725c7 2023-06-05)
Arch Linux
CLion 2023.1.3

**Comment by norru** [comment]
I have the opposite problem. Use after move is *not* being detected by the IDE. Eclipse reports the error in real time.

![image](https://github.com/intellij-rust/intellij-rust/assets/889291/b29e6c10-5bbd-4965-b405-bf5989e54408)

![image](https://github.com/intellij-rust/intellij-rust/assets/889291/3e54c74a-b8ca-41a6-ae69-ba75177a4e30)

As a workaround for CLion Rust plugin not reliably detecting compilation errors in the editor I'm running now Eclipse and IntelliJ side by side. I'm also going to try and run VS code (both Eclipse and VS code use rust-analyzer to accurately detect compiler errors in real time)

**Comment by Maksim20023** [comment]
Hi @norru ! Thank you for the report.
I reproduced the described issue in my environment. This is a false negative case of the "use moved value" error, so I've created #10823. Please subscribe to it so you can stay informed.
