### ISSUE TITLE
What about using WSL Rust?

### ISSUE THREAD

**Issue by concatime** [intellij-rust/intellij-rust#1171]
Hi. I'm trying to figure out how to use rustc & cargo from my WSL, where I installed rust, and works perfectly. In fact, I don't want to install Rust on Windows.
> https://medium.com/@bgourlie/cross-platform-development-on-windows-is-suddenly-awesome-da863a28fa1e

**Comment by alygin** [comment]
Unfortunately, you cannot use all the plugin features in such environment at the moment.

I'm not aware of all the Windows-Linux interoperability details and have no such setup on hand to check it, but will try to guess what must be implement in order to support it:

- Use `bash -c` to execute cargo and rustup commands.
- Use additional tricks to export environment variables to Linux when we execute a command.
- Require to keep the toolchain in some directory that is visible to Windows (for instance, somewhere in `/mnt/{disk}/...`) to make the file paths mapping possible in both directions.

**Comment by concatime** [comment]
I fooled IntelliJ Idea for using git. In fact, I set the path of git as /git.bat. And in the file c:\git.bat, i made this:
> @bash -c 'git %*'

Maybe we could do something like this as a hack for rust, pending for a real solution.

**Comment by alygin** [comment]
Unfortunately, such trick won't be enough to make the plugin work with WSL because it heavily relies on metadata obtained from various cargo commands. Such metadata include paths to source code of external libraries and paths to components of your own project. These paths must be somehow mapped automatically between Win and Linux. Other point of concern is environment variables that also play role in how the plugin works. The to-do list is above and I think there's a good chance it's incomplete.

**Comment by philippkeller** [comment]
I needed this, so I hacked together a solution which currently works on my machine: [rustup-toolchain-proxy](https://github.com/philippkeller/rustup-toolchain-proxy). I'm curious if anyone else gets this running. 

It uses the proxy characteristics of rustup and puts binaries within the rustup toolchain which run `bash.exe -c "cargo ..."`. What currently works:

- proxying to the cargo/rustc/rustdoc binaries within the WSL over `bash.exe -c ...`
- translating Linux paths to Windows path, e.g. "/home/linux_user/..." to: "C:\Users\windows_user\AppData\Local\lxss\home\linux_user.."

This makes now WSL's rust usable in IntelliJ. Compile/Run/Tests/... work, the line numbers in errors are clickable. Also there are "play buttons" next to `main()`, tests, etc.

@alygin can you provide me with a list of all commands which the rust plugin calls. Currently I only handle the path conversions of `cargo metadata` and `rustc --print sysroot` but I guess there are some other cases which need special handing.

**Comment by KelsonBall** [comment]
For anyone coming to this thread to check for compatibility, In May 2018 this tool worked for me out-of-the-box on WSL

**Comment by Marqin** [comment]
CLion has option to use C++ toolchains from WSL and achieves that by running commands via ssh, so maybe that option could be possible here too?

**Comment by DrizztVD** [comment]
I'd like this too. The workaround does not format the code properly it appears.

**Comment by bubuker** [comment]
What is the state of the WSL support in rust plugin?
Is it possible to use with the CLion 2018.3.3 ?

**Comment by vlad20012** [comment]
No progress for now.

**Comment by JorisBolsens** [comment]
👍 this would make life much easier for me as well

**Comment by bavalpey** [comment]
I'd love to see this work.  I try to exclusively use the wsl paths for all of my coding languages. I have found that it just works more smoothly.
It looks like supporting language servers won't make it into the next iteration plan.

https://github.com/Microsoft/vscode/issues/22663#issue-214362953 is a similar request to this, and it seems to have some support as well.

**Comment by thavlik** [comment]
This would be a great feature. I tried configuring CLion earlier today to debug using WSL and wasn't able to get the cargo command to use debian.exe instead of cmd.exe. I've been using debian.exe in the integrated terminal to write and debug rust for weeks now. Debugger support would make this even comfier :)

**Comment by sampleref** [comment]
Yes, CLion to support rust tool chain from WSL would be a great feature. Me too expecting the same

**Comment by bertonha** [comment]
on Visual Studio Code has a new plugin for connect on WSL or Docker
https://code.visualstudio.com/docs/remote/wsl

Would be amazing if we could have something similar on Intellij products

**Comment by richwandell** [comment]
T+1 

I just tried this out and no luck debugging using rust plugin for clion and wsl. This would be a great feature.

**Comment by gian21391** [comment]
+1
Being able to debug on Windows using WSL would be great.

**Comment by nikakis** [comment]
+1
Support rust tool chain from WSL

**Comment by es50678** [comment]
+1
Support rust tool chain from WSL

PS: Anyone know the sideffects of installing rust on windows while having it installed in WSL?

**Comment by kbec** [comment]
+1
Support rust tool chain from WSL

**Comment by kterhorst** [comment]
+1 ;)

**Comment by njasm** [comment]
+1

**Comment by Dongsheng-LI** [comment]
+1
Support rust tool chain from WSL

**Comment by njasm** [comment]
there is a pull request already waiting to be tested/accepted #4797

**Comment by oribenshir** [comment]
+1

**Comment by resodo** [comment]
+1

**Comment by npv3s** [comment]
+1

**Comment by LooMaclin** [comment]
+1

**Comment by paulcosma97** [comment]
+1

**Comment by xxchan** [comment]
+1

**Comment by RoBiK75** [comment]
+1

**Comment by aspenluxxxy** [comment]
I think it'd be better for y'all to just react with 👍 rather than posting +1, as posting +1 will notify _every subscriber_

**Comment by coolxxy** [comment]
+1
Please support rust tool chain from WSL

**Comment by akainth015** [comment]
I'd like to float #5014 back up since people seem to be missing seeing it. To use it effectively, clone the branch, build the plugin, and install it in CLion from your disk.

**Comment by sgrust01** [comment]
+1
rust tool chain from WSL

**Comment by suxiaoshao** [comment]
+1
rust tool chain from WSL

**Comment by Bobbbay** [comment]
Guys, gals, human beings (or Aliens are welcome too), spamming +1 is fun, but I don't think it will get us somewhere. Let's collaborate, identify the issues, and brainstorm instead!

**Comment by TheMushrr00m** [comment]
+1

**Comment by Sherlock-Holo** [comment]
even enable the org.rust.wsl feature, use the `\\wsl$\Archlinux2\usr\bin` can detect the std library path but when click OK, it will report invalid toolchain  location: can't find Cargo in \\wsl$\Archlinux2\usr\bin

**Comment by AllenPocketGamer** [comment]
> invalid toolchain

+1

**Comment by BratSinot** [comment]
Hello there!

Where I can find `org.rust.wsl`? No such option:
![image](https://user-images.githubusercontent.com/3810015/118272824-da5fbc00-b4cb-11eb-9c85-36db66a03acd.png)

**Comment by khaledh** [comment]
> Where I can find `org.rust.wsl`? No such option:

The feature is not released yet. It seems that it will be released in a few days as part of v147: https://github.com/intellij-rust/intellij-rust/milestone/55?closed=1

**Comment by Undin** [comment]
> even enable the org.rust.wsl feature, use the \\wsl$\Archlinux2\usr\bin can detect the std library path but when click OK, it will report invalid toolchain location: can't find Cargo in \wsl$\Archlinux2\usr\bin

@mchernyavsky could you take a look?

**Comment by jmcelwain** [comment]
Same issue on Arch as noted above. Here's the tail from the logs:

```
2021-05-20 22:58:48,334 [1138019]   WARN - rust.openapiext.CommandLineExt - Failed to run executable 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Program Files\JetBrains\IntelliJ IDEA 2021.1\jbr\bin\rustc.exe" (in directory "\\wsl$\Arch\home\jem\src"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:385)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:100)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:48)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:24)
	at org.rust.cargo.runconfig.RsCapturingProcessHandler.<init>(RsCapturingProcessHandler.kt:12)
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:32)
	at org.rust.cargo.toolchain.tools.Rustc.getSysroot(Rustc.kt:44)
	at org.rust.cargo.toolchain.tools.Rustc.getStdlibPathFromSysroot(Rustc.kt:51)
	at org.rust.cargo.toolchain.tools.Rustc.getStdlibFromSysroot(Rustc.kt:56)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel$update$1.invoke(RustProjectSettingsPanel.kt:121)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel$update$1.invoke(RustProjectSettingsPanel.kt:34)
	at org.rust.openapiext.UiDebouncer$run$1.run(ui.kt:42)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\JetBrains\IntelliJ IDEA 2021.1\jbr\bin\rustc.exe" (in directory "\\wsl$\Arch\home\jem\src"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:458)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:381)
	... 29 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 32 more
2021-05-20 22:58:51,277 [1140962]   INFO - s.impl.wsl.WslFileWatcher.Arch - Watcher terminated with exit code 0 
2021-05-20 22:58:53,228 [1142913]   INFO - rust.openapiext.CommandLineExt - Executing `C:\WINDOWS\system32\wsl.exe --distribution Arch --exec /bin/sh -c "export PATH=\"/usr/bin:$PATH\" && /usr/bin/rustc --version --verbose"` 
2021-05-20 22:58:53,466 [1143151]   INFO - rust.openapiext.CommandLineExt - Executing `C:\WINDOWS\system32\wsl.exe --distribution Arch --exec /bin/sh -c "export PATH=\"/usr/bin:$PATH\" && cd /home/jem/src && /usr/bin/rustc --print sysroot"` 
2021-05-20 22:59:03,989 [1153674]   WARN - options.ex.ConfigurableWrapper - Cannot find extension point com.intellij.compilerSettingsFactory in Project(name=src, containerState=COMPONENT_CREATED, componentStore=\\wsl$\Arch\home\jem\src) 
```

**Comment by jmcelwain** [comment]
Did a little digging on problem with Arch. Not sure how rustup works on other distros, but in arch, `/usr/bin/rustc` is a symlink to `/usr/bin/rustup`, and when we check whether the toolchain path is valid, there's a check to ensure that `/usr/bin/rustc` is a file. This eventually delegates to `sun.nio.fs.AbstractFileSystem#isRegularFile`, which throws and swallows a `java.nio.file.NoSuchFileException`. Looking at the stack trace, it's going through the windows filesystem provider, so I assume that this is whackiness with trying to read symlinks on the WSL partition from Windows.

Not sure what the fix is here, perhaps the symlink can be followed prior to running the check. May mess around later and see if I can come up with a patch.

**Comment by mchernyavsky** [comment]
@jmcelwain Thanks for the detailed explanation! It should fix the problem - https://github.com/intellij-rust/intellij-rust/pull/7268.

**Comment by jmcelwain** [comment]
@mchernyavsky  Way easier than I thought! Thanks so much for the patch.

**Comment by jmcelwain** [comment]
Unfortunately, I don't think delegating to `java.io.File` works. Just tested on master and this is still broken:
![image](https://user-images.githubusercontent.com/10366310/120031784-de590700-bfbe-11eb-9433-db495c502268.png)

I did a little more digging and discovered https://github.com/microsoft/WSL/issues/4868, which I believe is a related upstream issue. Unfortunately I'm very unfamiliar with Windows, but my debugging in powershell (see screenshot in linked issue) suggests this is just broken in WSL2.

I realize that 99% of users of this feature will use Ubuntu, so I appreciate your spending time trying to get this working for Arch. Please let me know if I'm misunderstanding something.

**Comment by mchernyavsky** [comment]
@jmcelwain Very strange. It works for me:

<img width="1218" alt="Screenshot 2021-05-28 at 22 42 48" src="https://user-images.githubusercontent.com/6079006/120034732-29e2d380-c006-11eb-9e2a-54f1ff4ca0cd.png">

**Comment by jmcelwain** [comment]
@mchernyavsky Oh great, what a mystery. I'm on build `21390.1`, which is pretty fresh. Let me do a clean build / sanity check again.
