### ISSUE TITLE
Is it meant to work with CLion 2017?

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#1361]
Because I couldn't find how to configure a rust project. CLion does not have modules and new/open project dialogs do not mention Rust:

<img width="808" alt="2017-06-20_1729" src="https://user-images.githubusercontent.com/28969/27338664-7fe15716-55de-11e7-9bb3-7b40caf26fc8.png">
<img width="691" alt="2017-06-20_1730" src="https://user-images.githubusercontent.com/28969/27338669-82323756-55de-11e7-9e82-82de96d5afba.png">

CLion is 2017.1.3.

**Comment by matklad** [comment]
There's **import from sources** action in CLion which somewhat works, but in general development with CLion is not super convenient at the moment, because it really assumes that you use CMake :(

**Comment by stepancheg** [comment]
In that case intellij-rust page should probably not recomment using "any" IDE and do not mention CLion.
<img width="991" alt="2017-06-20_1738" src="https://user-images.githubusercontent.com/28969/27339068-70714be6-55df-11e7-93a5-e5a40ffb178b.png">

**Comment by johnthagen** [comment]
Also should say 2016.2 and newer, not 2016.1 and newer I think.

**Comment by ph03** [comment]
Having the same problem that clion assumes I have a cmake-based C/C++ project instead of a rust project. This is a little bit sad, as the (preliminary) rust debugger is currently only supported in clion and not in IDEA.

**Comment by matklad** [comment]
>This is a little bit sad,

I would rather say that the amount of grief caused by this is immeasurable! Sorry about that, we are trying to fix this, but unfortunately it's more complicated then "write some code to make things work" ;(

**Comment by khionu** [comment]
Would it be possible to provide a default CMakeLists file that basically forwards the build work to cargo? Not the best solution, but it would at least prevent errors on setup of a new project.

**Comment by matklad** [comment]
I believe this would be fixed properly in one of the following releases of CLion.

cc @Undin

**Comment by vlad20012** [comment]
CLion EAP 2018.1 with correct Intellij-Rust support will be released very soon, expected this week! 
You can track it here https://blog.jetbrains.com/clion/tag/eap/

**Comment by khionu** [comment]
I'm sorry, what exactly is coming with that release?

**Comment by vlad20012** [comment]
@khionu 
1. You will be free from CMake in Rust projects
2. You will be able to create Rust projects with CLion's "New Project" dialog (just like in IDEA)

**Comment by Undin** [comment]
> You will be able to create Rust projects with CLion's "New Project" dialog (just like in IDEA)

I think "just like C++ project" or "just like in other small IDEs" is more correct :)

**Comment by khionu** [comment]
Ahh, thanks for the clarity!

**Comment by vlad20012** [comment]
CLion EAP 2018.1 just released. You can download it for free with JetBrains Toolbox app or from https://blog.jetbrains.com/clion/2018/01/clion-starts-2018-1-eap-wsl-cpp17-cmake/

**Comment by LaRueGT** [comment]
I'm very pleased with 2018.1 EAP so far. It felt really good to choose 'rust project', have it find the tool chain, and just run.

**Comment by khionu** [comment]
Agreed. I think this has been addressed to the point where it can be closed

**Comment by steveklabnik** [comment]
I am still having issues with the 2018.1 EAP. If I import a project, it still assumes CMake, and while I can set up a "cargo run", it still doesn't seem to think it's a rust project, there's no option to set a rust toolchain.

**Comment by Undin** [comment]
@steveklabnik you used `Import project from Sources` option at welcome screen, didn't you?
If yes then it's expected (but very confusing, sorry =( ) behavior - this option really assumes that importing project is CMake project.
To import rust project just open it via `Open` option at welcome screen

**Comment by Undin** [comment]
@steveklabnik you can also find answers to some basic questions about IDE [here](https://intellij-rust.github.io/docs/quick-start.html) (including import in CLion)

**Comment by steveklabnik** [comment]
Yes, using "Import from project sources", this happens.

> but very confusing, sorry=(

It's all good! :)

Yeah, I read the quick start, but the screenshots aren't the same. If I "Import project from sources"

![clion1](https://user-images.githubusercontent.com/27786/36259589-a392a07e-122c-11e8-8704-e7e481a6e004.png)

then i get a Cmake project, no matter what

![clion2](https://user-images.githubusercontent.com/27786/36259595-aa8beb92-122c-11e8-853f-88ddeba7859d.png)

The screenshot at "Use from existing sources import." in the quickstart guide never appears.

**Comment by matklad** [comment]
@steveklabnik I believe the first step is wrong :-) "Import from source" will **not** work: "import" in this context mean "try to figure out project structure using heuristics and create a CMake for it".

What you need is **Open project**

![](https://intellij-rust.github.io/assets/quick-start/clion-import-project.png)

**Comment by steveklabnik** [comment]
ah ha! that works great!

sorry for being a noob :)

**Comment by johnthagen** [comment]
@matklad Curious what you're up to now that you've moved on from Jetbrains. Still going up be involved with Rust? Thanks for all of your work on Intellij Rust!

**Comment by matklad** [comment]
@johnthagen replied via DM on gitter for reasons 😆

**Comment by aschampion** [comment]
In Clion 2017.3 if I choose "Open" and try to open either a Rust project directory or the `cargo.toml` inside it nothing happens, I just get returned to the menu. Tried deleting the cache directories (`~/Library/Caches/CLion2017.3/`), etc., with no success. Tried with many Rust projects.

**Comment by khionu** [comment]
Gonna bump my previous comment: now that the support is working as expected, it seems appropriate for this issue to be closed, and for any subsequent issues to be their own.

**Comment by Undin** [comment]
> Gonna bump my previous comment: now that the support is working as expected, it seems appropriate for this issue to be closed, and for any subsequent issues to be their own.

Reasonably :)

**Comment by spease** [comment]
Hi, just wanted to note that the Quick Start still has not been updated to specify using Open Project instead of Import. I've assumed for weeks that the plugin was just broken for the current version until I took another stab at it today.

**Comment by spease** [comment]
You mean the section that says "You can also import existing project from source." and shows a screenshot of clicking the Import button...?

**Comment by Undin** [comment]
Okay, I think we should specify that this part of the tutorial is only for IDEA to avoid such misunderstanding

**Comment by spease** [comment]
Yeah, I've never used IntelliJ before so I don't know anything.about the different products, and frankly it's so far seemed very confusing and full of dead ends. I specifically wanted to use the debugger, but it seems to require manual setup and there are no instructions for Windows. This was after manually setting up a build target to be able to even run it. And it took some googling to figure out which to choose (debugger sounded like it only worked in CLion).

I really just want a quick start guide that tells me exactly which product is most well-supported and how to get it fully functional. After I can be fully productive, then I'll worry about tweaking everything or trying different products that might integrate with other languages.

**Comment by khionu** [comment]
This conversation isn't suited for this issue, or really the context of a GitHub issue at all. I'd recommend asking in a Rust community, such as [this Discord](https://discord.me/rust-lang) or irc.mozilla.org#rust

**Comment by matklad** [comment]
@khionu FWIW, we are perfectly fine discussing anything in the issues in this repository :) 

However, more open ended discussion indeed could be better suited for our gitter: https://gitter.im/intellij-rust/intellij-rust

Note that developers of the plugin don't frequent rust irc channels that much :-)
