### ISSUE TITLE
SDK madness

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#224]
We have rather haphazard treatment of Rust SDK now.

Some facts:

There is no such thing as Rust SDK. `rustc` and `cargo` are independent programs. `cargo` uses whichever version of `rustc` happens to be in `PATH`. This can be overridden via cmdline switch/env variable. There is no official rule that `rustc` and `cargo` must reside in the (same) `bin` folder. 

Some current coincidences:

Jps does not use SDK, it uses cargo from `PATH`. 

~~Cargo import GUI asks for a path to SDK, but *does not* setup SDK for project~~.

Despite the aforementioned question in GUI, we use `cargo` from `PATH` to import the project.

**Comment by alexeykudinkin** [comment]
Fixed 2 latter concerns with `c4e2252`.

**Comment by alexeykudinkin** [comment]
So, we'd need just to re-reail JPS.

**Comment by matklad** [comment]
I'm not sure that "Cargo import GUI asks for a path to SDK, but does not setup SDK for project." is fixed: if I try to import a cargo project, the Rust SDK is still not created.

**Comment by alexeykudinkin** [comment]
Misintepreted your statement. Taking it back.
