### ISSUE TITLE
"Cannot move" error displayed by IDE while code compiles just fine

### ISSUE THREAD

**Issue by tongohiti** [intellij-rust/intellij-rust#3429]
## Environment

* **Intellij-Rust plugin version:** v0.2.92.2116-183 (latest stable at the moment of creating this issue)
* **Rust toolchain version:** 1.32
* **IDE name and version:** CLion 2018.3.4
* **Operating system:** Windows 7 x64

## Problem description
![image](https://user-images.githubusercontent.com/15714232/53169445-53725080-35ee-11e9-92e9-e596347f3f10.png)

## Steps to reproduce
Here is the code:
```
struct MyVec<T: Copy> ([T; 2]);

trait SomeTrait: Copy {}

impl<T: Copy> MyVec<T> {
    pub fn new(x: T, y: T) -> MyVec<T>
        where T: SomeTrait // <<--- CAUSE IS HERE
    {
        MyVec([x, y])
    }

    pub fn xy(&self) -> (T, T) {
        let MyVec(v) = self;
        (v[0], v[1])
    }
}
```
IDE highlights attempt to use `v[0]` (and `v[1]`) as "Cannot move" error despite `T: Copy`.

Rust compiler accepts this code just fine: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1eac5a64c5ad31088a8fadc195e4d191

When the line with comment "CAUSE IS HERE"is removed the error disappears.

**Comment by tongohiti** [comment]
Current nightly version of plugin - v0.2.93.2555-183-nightly - same issue.

**Comment by ortem** [comment]
Looks like it is fixed somehow already. @tongohiti thank you for reporting, please let us know if there are still some problems with our analysis.

**Comment by karlbeecken** [comment]
Hi! I'm still encountering this problem on 2023.1.3 (`#CL-231.9011.31`), see screenshot:
<img width="853" alt="image" src="https://github.com/intellij-rust/intellij-rust/assets/32744028/61419fb8-b91c-4c3a-8406-f2315aa56c3a">

Rust plugin version is `0.4.195.5408-231`.

Code compiles totally fine, there aren't any warnings or anything from cargo/rust compiler itself.

Can someone help me?

**Comment by karlbeecken** [comment]
Thank you, I didn't find the issue – this one is 2nd result at Google, so hopefully any other people will now also see this :)

**Comment by KianBrose** [comment]
Still an issue btw
