### ISSUE TITLE
Ranges have no completion for Iterator methods

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#3587]
## Environment

* **Intellij-Rust plugin version:** v0.2.94.2119-191
* **Rust toolchain version:** 1.33.0 (2aa4c46cf 2019-02-28)
* **IDE name and version:** IntelliJ IDEA 2019.1 (Ultimate Edition) Build #IU-191.6183.62, built on March 21, 2019
* **Operating system:** macOS 10.14.3

## Problem description

I have a range and I would like to call some `Iterator` methods on them, for instance:
`let result: Vec<_> = (0..1009).map(|i| i + 1).collect();`

There's no completion for those methods:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/2690773/54885547-07812880-4e86-11e9-9e9b-82b49ea64c66.png">

The completion does not start working even after the first iterator method is called:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/2690773/54885610-d1907400-4e86-11e9-906d-d778cd1c4d82.png">

even though now the plugin allows to navigate into `map` method to see its definition.

Might be good to check other methods for ranges also.

**Comment by vlad20012** [comment]
I didn't checked, but I guess it's related to macros and should be fixed with #3015

**Comment by SomeoneToIgnore** [comment]
I suspected the same, but wanted to have an issue just in case it's not related.
I resume that https://github.com/intellij-rust/intellij-rust/issues/3590 is also macros-related.

**Comment by perryprog** [comment]
This is still an issue even though #3015 has been merged. Can reproduce on nightly and stable.

**Comment by Undin** [comment]
@perryprog Did you enable experimental macro engine?
You can do it via `Preferences | Languages & Frameworks | Rust | Expand declarative macros` option
![image](https://user-images.githubusercontent.com/2539310/58436688-4f633c80-80cf-11e9-9bcf-0f81bf30f46b.png)

**Comment by perryprog** [comment]
No. This fixes it; I guess this issue can be closed now?

**Comment by Undin** [comment]
@perryprog We'll close all issues related to new macro expansion engine when it will be a default option, i.e. when #3628 will be closed

**Comment by Undin** [comment]
@perryprog BTW don't hesitate to provide feedback about new macro expansion engine.
It will help us to polish it and make the default option
I think #3628 is the best place for such feedback

**Comment by perryprog** [comment]
Sounds good, I’m excited! So far it’s a great improvement over the default one.

Thanks,

— Perry
