### ISSUE TITLE
Modules Index

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#372]
What is the current status of `RustModulesIndex`? Is it supposed to work, or does it still refer to itself during construction? 

Sometimes it does not work at the moment. Here is a test case:

* `git clone https://github.com/matklad/rustraytracer`
* open `src/main.rs`
* Ctrl+click `Regex` in `use regex::Regex`
* no resolve happens

Looks like the resolve fails because [this guy](https://github.com/intellij-rust/intellij-rust/blob/97ead16437154f62b2e82df9128b480ea08e5f9f/src/main/kotlin/org/rust/lang/core/resolve/indexes/RustModulesIndex.kt#L21) returns `rustraytracer/src/main.rs` as a super for `regex/src/lib.rs`, while it should return `null` because `regex/src/lib.rs` is a crate root:

```
super for /home/user/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/regex-0.1.58/src/lib.rs
is /home/user/projects/rustraytracer/src/main.rs
```

I don't understand how this can happen, but looks like `RustModulePath` can be ambiguous. 

What is our plan regarding ModulesIndex?

* We can switch to `FileIncludeIndex`, if we stop using `JarFileSystem` (and we do not *really* need it).
* We can simplify `ModulesIndex` and use file names and offsets a-la `FileIncludeIndex` instead `ModulePath` and `QualifiedNames` which seem to be the root of our problems with the index. 
* We can fix current implementation.

**Comment by matklad** [comment]
>Ctrl+click Regex in use regex::Regex

This is actually non-deterministic, you may have to "invalidate caches and restart" couple of times to trigger the error.

**Comment by matklad** [comment]
I get

`ERROR: Index org.rust.lang.indexes.RustModulesIndex violates equals / hashCode contract for Value parameter`

with the latest EAP.

**Comment by alexeykudinkin** [comment]
Should be fixed by now.

**Comment by matklad** [comment]
Still get contract violation with EAP for any test in `RustStdlibResolveTestCase`:

```
ERROR: Index org.rust.lang.indexes.RustModulesIndex violates equals / hashCode contract for Value parameter
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.util.indexing.MapReduceIndex.checkValuesHaveProperEqualsAndHashCode(MapReduceIndex.java:755)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:456)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1656)
	at com.intellij.util.indexing.FileBasedIndexImpl$19.run(FileBasedIndexImpl.java:1586)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1541)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1526)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1063)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:333)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The assert looks like this:

```Java
          if (!(Comparing.equal(value, deserializedValue) && (value == null || value.hashCode() == deserializedValue.hashCode()))) {
            LOG.error("Index " + myIndexId.toString() + " violates equals / hashCode contract for Value parameter");
          }
```

**Comment by matklad** [comment]
But otherwise it works fine!
