### ISSUE TITLE
10 second pauses while typing in my medium-sized project

### ISSUE THREAD

**Issue by xrl** [intellij-rust/intellij-rust#3780]
## Environment

* **Intellij-Rust plugin version:** `v0.2.97.2123-191`
* **Rust toolchain version:** `rustc 1.36.0-nightly (00859e3e6 2019-04-29)`
* **IDE name and version:**
```
IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```
* **Operating system:** See above

Also relevant, my changes to the VM Options:

```
# custom IntelliJ IDEA VM options

-Xms4g
-Xmx12g
-XX:ReservedCodeCacheSize=900m
-XX:+UseCompressedOops
-Dfile.encoding=UTF-8
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=200
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-Djdk.http.auth.tunneling.disabledSchemes=""
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Xverify:none

-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof
```

## Problem description

I am working on a project (private code repo, sorry) and as I'm typing the browser will pause. This is a 5-10 second pause. The CPU in OS X Activity Monitor will show 150-200% CPU utilization. Then the pause ends and whatever keystrokes were buffered up are put in. This pause is only during typing, not code exploring with the command button.

Here is a screenshot of the intellij activity monitor during a pause:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/693059/57101467-4b6e1580-6cef-11e9-92bc-741e92269fb5.png">

and then a bunch of things flash after the pause but I don't have time to screenshot before they disappear.

I thought it might be my JVM heap isn't large enough? OS X shows memory allocated to intellij stuck at around 5.2GB, that's the same value I've seen between numerous intellij restarts.

## Steps to reproduce

Not sure, do you have tips? Do you need access to the code base to see if I'm using exotic corners of the rust language?

In any case, here is my Cargo.toml:

```
[package]
name = "dracula"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]
edition = "2018"

[dependencies]
parquet = { git = "https://github.com/tureus/arrow.git", branch = "parquet_derive" }
parquet_derive = { git = "https://github.com/tureus/arrow.git", branch = "parquet_derive", features = ["chrono", "uuid"] }
reqwest = "0.9"
serde = { version = "1.0", features = [ ] }
serde_derive = "1.0"
serde_json = "1.0"
docopt = "1.0"
diesel = { version = "1.0.0", features = ["postgres", "32-column-tables", "numeric", "chrono", "uuid"] }
bigdecimal = "0.0.14" # gotta match the diesel version, try `cargo tree`
chrono = { version = "0.4", features = ["serde"] }
uuid = "0.6.4"
hashbrown = { version = "0.1", features = ["serde"] }
lazy_static = "1"
pretty-bytes = "0.2"
rusoto_core = "0.36.0"
rusoto_s3 = "0.36.0"
futures = "0.1"
url = "1.7"
# Needed for Postgres.
openssl = "*"
openssl-probe = "0.1.2"

[profile.release]
#lto = true
#debug = false
#codegen-units = 1
#panic = "abort"

#[[bin]]
#name = "dracula"
```

**Comment by xrl** [comment]
Here is a screenshot immediate after the pause:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/693059/57102217-eca99b80-6cf0-11e9-854f-456783f65b21.png">

**Comment by amakeev** [comment]
>I thought it might be my JVM heap isn't large enough? OS X shows memory allocated to intellij stuck at around 5.2GB, that's the same value I've seen between numerous intellij restarts.

It most likely mens that the JVM allocated the minimum application memory of 4 GB (`-Xms4g`) plus some extra for the JVM. Allocating such big heap (`-Xmx12g`) has also disadvantage as the JVM needs to work harder to collect the garbage.

Have you tried the default VM options with the default heap size?

**Comment by xrl** [comment]
What's interesting if that's the case, large heap is causing proportionally large GC time, I was running this config with previous builds of intellij for the last 6 months. I thought the only variable would be intellij/intellij-rust versions. I make sure to change VM options in every release of intellij (it's reset automatically when upgrading).

**Comment by vlad20012** [comment]
Could you please collect thread dumps when such pause happens? If it's really about 10s pauses, you can simply take it with `jstack` command-line utility. Just run `jstack <PID>` several times during such pause.

**Comment by vlad20012** [comment]
I guess it's the same problem as #3078 and so it should be fixed by #3834

**Comment by vlad20012** [comment]
@xrl Please, re-check the issue with the latest plugin version

**Comment by cemelo** [comment]
I have the latest version of the plugin and can confirm this is still an issue.

**Comment by vlad20012** [comment]
@cemelo Could you please collect thread dumps when such pause happens? If it's really about 10s pauses, you can simply take it with jstack command-line utility. Just run jstack <PID> several times during such pause.

**Comment by vlad20012** [comment]
@cemelo Oh, I just learned that thread dumps should be collected automatically. Could you please run ctrl+shift+A -> "Compress Logs" and then attach the archive?

**Comment by cemelo** [comment]
Sure. I'll do that and post it here when I see a freezing happening.
Thanks for looking into it, btw.

**Comment by cemelo** [comment]
@vlad20012 I just emailed you the thread dumps.

**Comment by vlad20012** [comment]
@cemelo I've received it. There is useful information. Thanks! I'll try to think of something

**Comment by vlad20012** [comment]
@cemelo I tried to fix it with #4114. Please, try the latest nightly plugin (you can find instructions [here](https://intellij-rust.github.io/install.html)).

**Comment by cemelo** [comment]
Thank you @vlad20012! I'll try it out and report back here.

**Comment by xahon** [comment]
I noticed a long lag after adding missing lifetime specifiers

**Comment by cemelo** [comment]
@vlad20012 After upgrading to nightly and using it for a while, I didn't notice long unbearable lags anymore. There's still a lag here and there, but about the same length/frequency as the ones I get using IntelliJ with Scala.

**Comment by splix** [comment]
I had the same issue I think. 5-10 seconds pause after almost any change to signature/type/etc (for a fairly simple Rust project, just few files). Sometimes it was freezing for more than a few minutes, so I had to apply Force Quit to IntelliJ IDEA. 

I had tried nightly build of the plugin and I _can confirm the issue is mostly fixed_. "Mostly" because it still has 0.5-1 second lag sometimes, but that's more or less acceptable.
