### ISSUE TITLE
Repeat build/error messages when (Ctrl + F9)

### ISSUE THREAD

**Issue by andreevlex** [intellij-rust/intellij-rust#3843]
## Environment

* Intellij-Rust plugin version: v0.2.97.2123-191
* Rust toolchain version: 1.34.1
* IDE name and version: IntelliJ IDEA 2019.1.2 (Community Edition)
* Operating system: Linux

## Problem description

Error messages are repeated when you run an building project by using Ctrl+ F9.

## Steps to reproduce

Output build console:

```bash
error[E0412]: cannot find type `Node` in this scope
  --> src/lib.rs:10:24
   |
10 |     fn root(&self) -> &Node;
   |                        ^^^^ not found in this scope

error[E0412]: cannot find type `Node` in this scope
  --> src/lib.rs:38:24
   |
38 |     fn root(&self) -> &Node {
   |                        ^^^^ not found in this scope

warning: unused import: `core::borrow::BorrowMut`
 --> src/lib.rs:1:5
  |
1 | use core::borrow::BorrowMut;
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error[E0412]: cannot find type `Node` in this scope
  --> src/lib.rs:10:24
   |
10 |     fn root(&self) -> &Node;
   |                        ^^^^ not found in this scope

error[E0412]: cannot find type `Node` in this scope
  --> src/lib.rs:38:24
   |
38 |     fn root(&self) -> &Node {
   |                        ^^^^ not found in this scope

warning: unused import: `core::borrow::BorrowMut`
 --> src/lib.rs:1:5
  |
1 | use core::borrow::BorrowMut;
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to 2 previous errors
```

**Comment by mchernyavsky** [comment]
When you build your project Rust project via `Ctrl-F9` IDEA just run `cargo build --all --all-targets` command. Cargo may duplicate some error messages when `--all-targets` attribute is used. You can prevent the use of `--all-targets` option (`Preferences > Languages & Frameworks > Rust > Cargo > Compile all project targets if possible`).

I filter out repeated errors/warnings in [this PR](https://github.com/intellij-rust/intellij-rust/pull/3926). The command's original output is shown in a separate window.

**Comment by qiujiangkun** [comment]
> When you build your project Rust project via `Ctrl-F9` IDEA runs `cargo build --all --all-targets` command. Cargo may duplicate some error messages when `--all-targets` attribute is used. You can prevent the use of `--all-targets` option (`Preferences > Languages & Frameworks > Rust > Cargo > Compile all project targets if possible`).
> 
> I filter out repeated errors/warnings in [this PR](https://github.com/intellij-rust/intellij-rust/pull/3926). The command's original output is shown in a separate window.

I fixed the problem by your means, but I still can see repeated warnings with --all-targets until now

**Comment by mchernyavsky** [comment]
Currently, the new build tool window (https://github.com/intellij-rust/intellij-rust/pull/3926) is experimental. You can enable it by setting `cargo.build.tool.window.enabled` variable to `false` (see `Actions > Registry...`). It should fix your problem.

**Comment by ratijas** [comment]
Good to know about "Compile all project targets if possible" checkbox. Thanks. The problem still persist on default fresh install today.
