### ISSUE TITLE
Name resolution and completion don't work with async_std/tokio/reqwest crates

### ISSUE THREAD

**Issue by hhggit** [intellij-rust/intellij-rust#4627]
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2149-192
* **Rust toolchain version:** 1.39.0
* **IDE name and version:** Clion 2019.2.1
* **Operating system:** Ubuntu 19.10

## Problem description

`#[cfg(feature = "...")]` in macros could not be found.

https://github.com/async-rs/async-std/blob/f611ceccc87aaf6b6cfb5bdee8bfffaffee5498f/src/utils.rs#L134-L144
https://github.com/async-rs/async-std/blob/f611ceccc87aaf6b6cfb5bdee8bfffaffee5498f/src/lib.rs#L203-L211

``` rust
/// Declares std items.
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! cfg_std {
    ($($item:item)*) => {
        $(
            #[cfg(feature = "std")]
            $item
        )*
    }
}

cfg_std! {
    // ...
    pub mod task;
}
```

## Steps to reproduce
The plugin cannot find the declaration of `block_on` to go. But it cound find after changing `cfg_std! {   pub mod task;} `to `#[cfg(feature = "std")]pub mod task;` .
``` rust
use async_std::task;

fn main() {
    task::block_on(async {
        println!("Hello, world!");
    })
}
```

**Comment by Undin** [comment]
> #[cfg(feature = "...")] in macros could not be found.

`cfg` attribute in macro call does not affect anything in this case.

@vlad20012 Looks like the plugin fails to resolve macros from `utils.rs` (except in `lib.rs` where the corresponding module is declared) so all modules declared inside the corresponding macro calls cannot be resolved

**Comment by vlad20012** [comment]
The issue has been known for a long time. The new macro expansion engine (#3628) doesn't solve it for now. Recently we discussed some possible solutions, so I'll try to prototype something.

**Comment by swarmer** [comment]
This is a hard blocker for me because it's common to have large chunks of code in macros like this, and intellij degrades into a very dumb editor (navigation/search fails) in these cases.

**Comment by caibirdme** [comment]
any update for this issue?

**Comment by s97712** [comment]
> any update for this issue?

+1

**Comment by dobrakmato** [comment]
Was looking to make a workaround by using `tokio` but it apparently also uses `cfg` inside marcos.

**Comment by UkonnRa** [comment]
Well, same issue when using `tokio = { version = "~0.2", features = ["full"] }`

**Comment by Undin** [comment]
It's fixed in #4914 and will be landed in the next release (I hope).
Note, intellisense features (name resolution, completion, etc) should work correctly only with new experimental macro expansion engine (see #3628).
So, let's keep this issue open until new macro expansion engine is enabled by default

**Comment by BratSinot** [comment]
Still not working (Clion 2021.1.1, Rust plugin 0.4.147.3871-211):
![image](https://user-images.githubusercontent.com/3810015/119122508-4051c380-ba37-11eb-876c-edaab9d9071a.png)
