### ISSUE TITLE
Some links in quick documentation are not resolved

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5374]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3092-201-nightly
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.13.6

## Problem description
The plugin can't resolve relative links in quick documentation when both documentation owner and link target are re-exported and link uses path between reexported names

## Steps to reproduce
For example, `Eq` link in `HashMap` documentation can't be resolved

```rust
use std::collections::HashMap;

fn main() {
    let map = HashMap::new();
}
```

**Comment by dima74** [comment]
@Undin looks like it was fixed some time ago?

**Comment by Undin** [comment]
Actually, no
It works because of the new link format. If you try to use rustc 1.43, it still won't work because the plugin incorrectly generates paths in case, when the item (`HashMap` in this case) is reexported and documentation links are written accounting this reexport
But probably, it's not worth fixing it because of the new format of documentation links
