### ISSUE TITLE
`Token` macro not found in syn crate

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#6236]
## Environment

* **IntelliJ Rust plugin version: 0.3.132.3395-202**
* **Rust toolchain version: 1.47.0**
* **IDE name and version: CLion 2020.2.4**
* **Operating system: Arch Linux**

## Problem description

```
[dependencies]
syn = "1"
```

```
use syn::Token;

fn main() {
    Token![where] // Unresolved reference: `Token`
				  // syn::token::Token? Alt+Enter
}
```

Replacing `syn::Token` by `syn::token::Token` leads to a compilation error. Macros must be imported from the crate root:

```
error: cannot find macro `Token` in this scope
 --> src/main.rs:5:5
  |
5 |     Token![where]
  |     ^^^^^
```

The macro not being found is acceptable. What's not acceptable is permanently suggesting I import `syn::token::Token`. As a workaround, it's possible to add `#[allow(unused_imports)] use syn::token::Token;`.

## Steps to reproduce

See above.

**Comment by Juici** [comment]
A workaround for this is to disable the lint, and just rely on the `cargo check` lints to cover unresolved references.

**Comment by dima74** [comment]
Fixed with [new name resolution](https://github.com/intellij-rust/intellij-rust/issues/6217) engine [enabled](https://github.com/intellij-rust/intellij-rust/pull/6378)

**Comment by sabbyX** [comment]
> Fixed with [new name resolution](https://github.com/intellij-rust/intellij-rust/issues/6217) engine [enabled](https://github.com/intellij-rust/intellij-rust/pull/6378)

It's still not fixed, already enabled `name resolution 2.0`

**Plugin version**:  0.3.139.3589-203-nightly
**IDE**: Clion 2020.3.1
**Operation system**: Windows 10
**Rust**: rustc 1.51.0-nightly (2987785df 2020-12-28)

---

![image](https://user-images.githubusercontent.com/61574665/104103559-bb0c1480-52c8-11eb-9273-d7cfb2cd19b4.png)

![image](https://user-images.githubusercontent.com/61574665/104103649-3b327a00-52c9-11eb-8f30-ea4c746d516c.png)

**Comment by Juici** [comment]
It is fixed, the import should be `syn::Token`, I was using it earlier
today.

**Comment by sabbyX** [comment]
> It is fixed, the import should be `syn::Token`, I was using it earlier today.

Strange, I'm pretty sure it is plugin issue (as it compiled/ran fine, even worked fine (`go to definition`) when tested in rust-analyzer). could you please specify your plugin version? or maybe I'm missing something :(

**Comment by Juici** [comment]
0.3.138.3572-203

**Comment by dima74** [comment]
@sabbyX could you please try to reproduce issue on empty project (like in issue description). And also please provide logs (`Help | Show Log in ...`)

**Comment by sabbyX** [comment]
You don't believe me how strange the reproduction of this issue,

I switched to version `0.3.138.3572-203`, it's working! to grab logs, I switched again to latest nightly, surprisingly it was working there too. I created a new project with the latest nightly. unfortunately, `go-to-definition` doesn't work there.

[idea.log](https://github.com/intellij-rust/intellij-rust/files/5792177/idea.log)

**Comment by dima74** [comment]
> I created a new project with the latest nightly

@sabbyX just to be sure - have you enabled new resolution engine in this project? Currently new name resolution engine has to be enabled in each project independently

**Comment by sabbyX** [comment]
> Currently new name resolution engine has to be enabled in each project independently

Oh, It seems like it's enabled by default when creating a new project on my machine ( _atleast on nightly_ ).
Well, Just to make sure, again created a new project with nightly again, the behaviour is the same as before.

https://user-images.githubusercontent.com/61574665/104213693-9779d300-545c-11eb-8ea6-0b7020de3013.mp4
