### ISSUE TITLE
cargo temporary toolchain overrides only allow "run"

### ISSUE THREAD

**Issue by C0D3-M4513R** [intellij-rust/intellij-rust#7748]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When doing x86 builds, everything, aside from Running the current configuration will be greyed out.
![image](https://user-images.githubusercontent.com/28912031/131216262-480fab45-840e-482f-bcba-731c2c9a9ce2.png)

## Steps to reproduce
0. Have a x86 rust toolchain, or run ` rustup toolchain install stable-i686` to install one.
1. Create a new binary rust project. (We need a exe, to debug)
2. Wait, for clion to load, and to create a run configuration
3. Edit the Run Configuration, by prepending `+stable-i686 ` to the command-line

For Testing you don't need any code nessesarily, but a hello-world programm would be advised.

**Comment by C0D3-M4513R** [comment]
If you set the Toolchain location, to use the i686 toolchain, then rust will compile and debug in x86 mode.
Thus it is not needed, to append `+stable-i686`, and everything works great.
Appending `+stable-i686`, whilst doing this fix, will still not work, for debugging.

**Comment by Undin** [comment]
Fixed in #7864

**Comment by C0D3-M4513R** [comment]
this is not fixed. This is still very much happening.
using version 0.4.164.4409-212 of Rust plugin.
![grafik](https://user-images.githubusercontent.com/28912031/156947598-4edcc426-26f4-431d-8e65-73f6cff4915d.png)
