### ISSUE TITLE
Support code completion for default functions in traits

### ISSUE THREAD

**Issue by kirillkh** [intellij-rust/intellij-rust#866]
```
trait X {
    fn a(&self) {
        self.b();  // <- code completion doesn't work after "self."
    }

    fn b(&self) {}
}
```

**Comment by himikof** [comment]
Duplicated by #875, should be fixed in f0a252d.

**Comment by matklad** [comment]
Yes, thanks @himikof !

**Comment by kirillkh** [comment]
Still not fixed for me in the latest plugin release (0.1.0.1385). Navigation between functions works now, but code completion doesn't. E.g.: [line 56 here](https://github.com/kirillkh/rs_teardown_tree/blob/41afe177c86466be2977211b4fc7e65e39457394/src/applied/plain_tree.rs).
