### ISSUE TITLE
Let else statements, showing an incorrect? linting error

### ISSUE THREAD

**Issue by codedcosmos** [intellij-rust/intellij-rust#9544]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** beta-x86_64-unknown-linux-gnu (rustc 1.65.0-beta.3)
* **IDE name and version:** Clion 2022.2.4 - Build #CL-222.4345.21
* **Operating system:** Ubuntu 22.04

## Problem description
Attempting to write code containing let else statements results in a red linting error:
`let else is experimental [E0658]`

## Steps to reproduce
Paste the following code below into a rust project in clion.

```rust
fn main() {
    println!("Hello, world!");

	let apple: Option<i32> = Some(32);

	println!("{:?}", apple);

	let Some(apple) = apple else {
		println!("No value");
		return;
	};

	println!("{:?}", apple);
}
```

## Other notes
My understanding is this was implemented a while ago based on a brief look at the [this issue](https://github.com/intellij-rust/intellij-rust/issues/7773). Would it be possible to disable this lint? `let else` isn't official yet but I feel as though the inspection should have an option to turn it off.

**Comment by mchernyavsky** [comment]
Looks like it is fixed in v181 by [this PR](https://github.com/intellij-rust/intellij-rust/pull/9480).

**Comment by vlad20012** [comment]
v181 will be released tomorrow btw

**Comment by ChzenChzen** [comment]
@vlad20012 still have the issue in  version `0.4.181.4965-222`.

**Comment by tnkemdilim** [comment]
`let else` has been stabilized in [1.65](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html). Any possibility the lint could be disabled?

**Comment by vlad20012** [comment]
@tnkemdilim, Hi! I don't see such errors with the latest plugin. What is your Rust plugin version? You likely just need to update it. 

![image](https://user-images.githubusercontent.com/3221931/204271110-9dda5e3a-9dcf-443b-873b-b5789a6e0b2b.png)

**Comment by tnkemdilim** [comment]
My bad. I'm still stuck on the `0.4.172`. I was on an older version of the IDEA which was still mentioning `0.4.172` was the latest plugin version. Updating IDEA to the latest fixed the issue. 

Thanks.
