### ISSUE TITLE
wrong type inference with GATs

### ISSUE THREAD

**Issue by Slarper** [intellij-rust/intellij-rust#9772]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4996-222
* **Rust toolchain version:** Visual Studio
* **IDE name and version:** CLion 2022.2.4
* **Operating system:** Windows 11

## Problem description
I made a Functor trait and test it. The program ran without warnings or errors but the plugin got a wrong return type inference from the Functor's map function.
![image](https://user-images.githubusercontent.com/98243861/202888656-eb8c67f7-9242-447b-ac82-59ae25d58766.png)
Look! It should be the `Option<String>`, but the type parameter inside was not inferred.

## Steps to reproduce
```rust
macro_rules! out {
    ($a:expr) => {
        println!("{}", $a)
    };
}

fn main() {
    let a: Option<String>= Some("114514".to_string());
    let b = Functor::map(a,
                         |mut x|-> String {
                             x.push_str("asd");
                             x
                         });
    match b {
        Some(x) => {out!(x)}
        None => {}
    }
}

trait Functor {
    type Unwrapped; // A
    type Wrapped<B>: Functor; // F B

    fn map<F, B>(self, f: F) -> Self::Wrapped<B> // F A -> (A -> B) -> F B
        where
            F: FnMut(Self::Unwrapped) -> B;
}

impl <A> Functor for Option<A> {
    type Unwrapped = A;
    type Wrapped<T> = Option<T>;

    fn map<F: FnMut(A) -> B, B>(self, mut f: F) -> Option<B> {
        match self {
            Some(x) => Some(f(x)),
            None => None,
        }
    }
}


```

**Comment by Undin** [comment]
@mchernyavsky should #8544 fix this issue?

**Comment by mchernyavsky** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/8544.

**Comment by Slarper** [comment]
![image](https://user-images.githubusercontent.com/98243861/207791378-ad3a7013-8638-4537-9d9f-764472962389.png)

Now it doesn't show an error but the rendering is still incorrect. Expect `Option<String>` here.

**Comment by Slarper** [comment]
ok. The lastest rust plugin update includes it.
https://intellij-rust.github.io/2022/12/19/changelog-185.html (first item)
