### ISSUE TITLE
IntelliJ IDEA enables nightly feature of thiserror on stable compiler

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#9880]
## Environment

* **IntelliJ Rust plugin version:** 0.4.185.5064-223-nightly
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.3 Ultimate Edition (IU-223.7571.182)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
When adding `thiserror` to a project, IntelliJ IDEA somehow enables the `provide_any` nightly feature in it, causing compilation to fail until `cargo clean` is run.

## Steps to reproduce
1. Create a new binary project
2. Add `thiserror = "1.0.37"` to its dependencies and click "Load Cargo Changes"
3. Once this is done and indexing is complete, run the project.

The result is compilation failing with

```
C:/Users/L/.cargo/bin/cargo.exe build --color=always --message-format=json-diagnostic-rendered-ansi --package idebug --bin idebug
   Compiling thiserror v1.0.37
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\L\.cargo\registry\src\github.com-1ecc6299db9ec823\thiserror-1.0.37\src\lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to 2 previous errors
Process finished with exit code 101
```

Performing `cargo clean` fixes this, allowing compilation to succeed. The project can then print "Hello, world!".

VSCode with rust-analyzer apparently hit this same issue https://github.com/dtolnay/thiserror/issues/192 which was fixed in an update at some point.

**Comment by bes** [comment]
Yeah, if you're wondering why "Run external linter to analyze code on the fly" isn't working anymore, this is it. `cargo clean` seems to fix it for now.

**Comment by ancwrd1** [comment]
Also happens with `rustix` crate. This is very annoying issue, most non-trivial projects suffer from this either via direct or indirect dependency on rustix/anyhow.

**Comment by Undin** [comment]
Should be fixed by #9901

**Comment by ancwrd1** [comment]
This issue still occurs with the latest version of the plugin and rustix crate:

```text
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.8/src/lib.rs:99:26
   |
99 | #![cfg_attr(rustc_attrs, feature(rustc_attrs))]
   |                          ^^^^^^^^^^^^^^^^^^^^
```

**Comment by ancwrd1** [comment]
Plugin version is 0.4.189.5234-223
Easy to reproduce:

```text
cargo init rustix-test
cd rustix-test
cargo add rustix
clion .
<try to build>
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.8/src/lib.rs:99:26
   |
99 | #![cfg_attr(rustc_attrs, feature(rustc_attrs))]
   |                          ^^^^^^^^^^^^^^^^^^^^

```

**Comment by ETKNeil** [comment]
I concur, this happen on the current build (0.4.189.5234-223) and it's way often, actually so far, even with cleaning, removing the target I have not been able to compile successfully a project depending on rustix with clion

**Comment by Undin** [comment]
Thanks for reporting!
I've filed separate issues #10186, since it slightly differs from the original one although the reason is the same
